### ISSUE TITLE
LYRX support for SLYR (Community Edition)

### ISSUE THREAD

**Issue by agiudiceandrea** [north-road/slyr#136]
**Describe the bug**

The plugin description: 

> ESRI Style, LYR, MXD, stylx, lyrx to QGIS symbology converter (Community Edition)

mentions the lyrx files as supported by the community edition of the plugin.
The lyrx files are listed in the Browser panel, anyway it seems they are not actually supported.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QGIS 3.26.0

**Comment by nyalldawson** [comment]
This is correct - you require a license for any of the ArcGIS pro file formats (for now).

**Comment by nyalldawson** [comment]
> Maybe it would be better to remove such file types from the description of the community edition of the plugin

I'm reticent to do that -- the functionality is there, it just needs a licence. The same situation applies to all the other plugins which require an API key like maptiler, google earth engine, google geocoders, etc. It may not be an ideal situation, but "pay to play" plugins are already rife through the plugin ecosystem.

At least with slyr you know the license fees go straight back into improving qgis 😝
