### ISSUE TITLE
slyr does not appear to work on mac OSX 

### ISSUE THREAD

**Issue by nickskelton2** [north-road/slyr#139]
Current QGIS and Current OSX
SLYR plugin is installed 

QGIS version: 3.26.2-Buenos Aires
QGIS code revision: b0f8302dbc
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
SLYR (community edition) version: 4.0.3
Algorithm started at: 2022-09-10T16:27:00
Algorithm 'Convert MXD/MXT to QGS' starting…
Input parameters:
{ 'INPUT' : '/Users/Shared/GIS Best Files/Vegetation/SVTM extant and pre 1750/NSW C1.1 M1 Aug 22/vegetation_svtm_nsw_extant_pct_quickview/SVTM_NSW_Extant_PCT.mxd', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

then nothing happens

same with .lyr

tried it on a few .lyr and mxb

Great work
Thanks

Nick

**Comment by nyalldawson** [comment]
You currently need a license for mxd conversion. Vector lyr conversion should work fine.

**Comment by nickskelton2** [comment]
Thanks for your reply

.lyr also just hangs

QGIS version: 3.26.2-Buenos Aires
QGIS code revision: b0f8302dbc
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
SLYR (community edition) version: 4.0.3
Algorithm started at: 2022-09-10T17:35:43
Algorithm 'Convert LYR to QLR' starting…
Input parameters:
{ 'INPUT' : '/Users/Shared/GIS Best Files/Vegetation/CPCP_SEED_Data/CPCP_EPBC_TEC_SEED.lyr', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'USE_RELATIVE_PATHS' : False }


Do you need any more info?

**Comment by nyalldawson** [comment]
Do you mind sharing the files?

**Comment by nickskelton2** [comment]
Nyall, 

Thank you for looking into this issue.
As requested 

This is the lyr file


From https://datasets.seed.nsw.gov.au/dataset/cpcp



A separate matter 
In NSW Australia there has been a major release of 2 new statewide vegetation layers

https://datasets.seed.nsw.gov.au/dataset/nsw-state-vegetation-type-map
And
https://datasets.seed.nsw.gov.au/dataset/nsw-state-vegetation-type-map-pre-clearing

Beware it is a 10Gb download
There will be a minor update soon

It will be used by many 1,000s of GIS users for many years many of the users will be small ecological consultant users like myself or members of the public. At the moment the .wms server is not working and may never work

I was hoping to supply the government authority with the QGIS legend description files for them to include with the download to encourage the use of QGIS and to not alienate existing QGIS users. 
Being a government agency they are ESRI focused. 

At the moment it only has .mxd files

If you haver time could you please make the QGIS legend files for these two layers so I can supply the files to the government to include with the data. 


Thanks

Nick

**Comment by nyalldawson** [comment]
Hey Nick,

Here you go! [SVTM_NSW_.zip](https://github.com/north-road/slyr/files/9580076/SVTM_NSW_.zip)

I can't reproduce the hang myself -- it could be due to some macos specific python issue :scream: . I did push one possible fix in a new update to this plugin (4.0.6), so could you test the latest version and let me know if you still get problems?
