### ISSUE TITLE
SLYR Python error on Mac 

### ISSUE THREAD

**Issue by jjthebb** [north-road/slyr#150]
MacBook Pro M1 Processor
iOS 13.4
QGIS  3.26.2 

When tyring to conver a .lry file into a .qml file the following error occurs: 

**Traceback (most recent call last):
              File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/gui/AlgorithmDialog.py", line 273, in runAlgorithm
              'parameters': self.algorithm().asMap(parameters, self.context)
             Exception: unknown**
             
Many thanks for your help

**Comment by nyalldawson** [comment]
Can you update your qgis version? This was a bug in qgis itself which is fixed in newer versions.

**Comment by jjthebb** [comment]
thank you, yes that fixed it. apologies.
